### PR TITLE
Write image update date earlier

### LINKED ISSUE #1139: Update screen: inconsistency in date of last OS update
- Device: Nexus 5
- Channel: rc
- Build: 2019-W18

### Steps to reproduce
Open Settings - Updates. Check the date of the last OS update that was installed and compare to the date it was actually installed.

### Expected behavior
The date of the last update should be the date when this update was actually installed on the  device, and it should not change.

### Actual behavior
The date of the last OS update changes as time passes. This date is always incremented to today's date when you open this page, even though the update may have been installed many days earlier.

When the next OS update gets installed the date of the previous one stops changing.

### PR DESCRIPTION
**Pull request by Flohack74**
This will fix ubports/ubuntu-touch#1139

### CODE REVIEW

**Comment by dobey** [comment]
Any chance to add a regression test for this, which fails without the change, and passes with?

**Comment by Flohack74** [comment]
Sure I can do this, my first time to do a test for ubuntu touch :)

**Comment by Flohack74** [comment]
By the way I am testing it today on my N5 to see if it really works, had to wait for the nightly devel.

File: tests/plugins/system-update/tst_updatemodel.cpp [hunk 1]
```diff
@@ -392,6 +392,47 @@ private slots:
...
+    void testClickUpdatedAtSetLate() {
+        auto update = createUpdate("id", 42);
+        update->setKind(Update::Kind::KindClick);
+        m_db->add(update);
+        m_model->setDownloaded(update->identifier(), update->revision());
+        auto update1 = m_db->get(update->identifier(), update->revision());
+        auto passed = update1->updatedAt() == QDateTime();
+        if (!passed)
+            QWARN("testClickUpdatedAtSetLate failed at early test!");
+        QVERIFY(passed);
```
Comment (dobey) [inline tests/plugins/system-update/tst_updatemodel.cpp]: Can you please revert these superfluous logging changes to the tests, so that it just does the QCOMPARE() again?

**Review by dobey — CHANGES_REQUESTED** [review]

**Review by dobey — APPROVED** [review]
